{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "bd5dc7d6-3b79-4776-a7fb-f2f17a02d74d",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-07-28 09:29:51.203 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:51.204 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:51.430 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\javila\\AppData\\Local\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2026-07-28 09:29:51.431 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:51.433 No runtime found, using MemoryCacheStorageManager\n",
      "2026-07-28 09:29:51.434 No runtime found, using MemoryCacheStorageManager\n",
      "2026-07-28 09:29:51.434 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:51.435 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:51.436 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:51.942 Thread 'Thread-3': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:51.947 Thread 'Thread-3': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.670 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.671 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.672 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.672 Session state does not function when running a script without `streamlit run`\n",
      "2026-07-28 09:29:54.673 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.673 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.673 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.674 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.675 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.676 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.676 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.677 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.678 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.678 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.681 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.682 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.683 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.683 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.684 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.684 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.685 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.686 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.687 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.688 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.688 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.689 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.690 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.690 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.691 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.691 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.692 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.692 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.693 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.693 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.693 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.694 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.694 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.695 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.695 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.696 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.697 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.697 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.698 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.698 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.699 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.699 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.700 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.701 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.701 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.703 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.704 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.704 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.705 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.706 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.706 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.706 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.707 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.708 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.708 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.709 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.709 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.710 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.710 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.711 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.711 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.712 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.712 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.712 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.713 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.713 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.714 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.715 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.716 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.716 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.717 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.717 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.718 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.718 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.718 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.719 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.720 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-28 09:29:54.720 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import requests\n",
    "import math\n",
    "import urllib.parse\n",
    "from datetime import datetime\n",
    "from PIL import Image\n",
    "\n",
    "# 🔗 TU URL DE GOOGLE APPS SCRIPT\n",
    "URL_API = \"https://script.google.com/macros/s/AKfycbzE2qSC4oR8zDa1pTyTjQfKFxsTHepWC3iW9JriiQ75laCFCQbs7iaceuH9sVP-XuDo/exec\"\n",
    "\n",
    "ruta_logo = \"logo.png\"\n",
    "icono_pestana = Image.open(ruta_logo) if os.path.exists(ruta_logo) else \"🏋️‍♂️\"\n",
    "\n",
    "st.set_page_config(page_title=\"Power Training - Personalizado\", page_icon=icono_pestana, layout=\"wide\")\n",
    "\n",
    "# Estilos visuales en modo oscuro\n",
    "st.markdown(\"\"\"\n",
    "    <style>\n",
    "        .stApp { background-color: #111111; }\n",
    "        h1, h2, h3, h4 { color: #ffffff !important; text-align: center; }\n",
    "        p, label, .stMarkdown { color: #dddddd !important; }\n",
    "        div[data-testid=\"stDecoration\"] { display: none; }\n",
    "    </style>\n",
    "\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "# --- MOSTRAR LOGO CENTRADO EN LA CABECERA ---\n",
    "if os.path.exists(ruta_logo):\n",
    "    col_l1, col_l2, col_l3 = st.columns([1, 1, 1])\n",
    "    with col_l2:\n",
    "        st.image(Image.open(ruta_logo), width=180)\n",
    "\n",
    "# --- FUNCIONES DE CÁLCULO FÍSICO Y SALUD ---\n",
    "def calcular_metricas(peso, estatura_cm, edad, sexo, cuello, cintura, cadera, meta):\n",
    "    estatura_m = estatura_cm / 100.0\n",
    "    imc = peso / (estatura_m ** 2)\n",
    "    \n",
    "    # % Grasa Corporal (US Navy Method)\n",
    "    try:\n",
    "        if sexo == \"Masculino\":\n",
    "            pct_grasa = 86.010 * math.log10(cintura - cuello) - 70.041 * math.log10(estatura_cm) + 36.76\n",
    "        else:\n",
    "            pct_grasa = 163.205 * math.log10(cintura + cadera - cuello) - 97.684 * math.log10(estatura_cm) - 78.387\n",
    "        pct_grasa = max(pct_grasa, 4.0)\n",
    "    except:\n",
    "        pct_grasa = 20.0\n",
    "\n",
    "    # Tasa Metabólica Basal (Mifflin-St Jeor)\n",
    "    if sexo == \"Masculino\":\n",
    "        tmb = (10 * peso) + (6.25 * estatura_cm) - (5 * edad) + 5\n",
    "    else:\n",
    "        tmb = (10 * peso) + (6.25 * estatura_cm) - (5 * edad) - 161\n",
    "        \n",
    "    mantenimiento = tmb * 1.375\n",
    "    \n",
    "    if meta == \"Perder Grasa\":\n",
    "        calorias = mantenimiento - 400\n",
    "    elif meta == \"Ganar Músculo\":\n",
    "        calorias = mantenimiento + 350\n",
    "    else:\n",
    "        calorias = mantenimiento\n",
    "\n",
    "    desvio_imc = max(0, imc - 22.0)\n",
    "    desvio_grasa = max(0, pct_grasa - (15.0 if sexo == \"Masculino\" else 22.0))\n",
    "    edad_metabolica = int(edad + (desvio_imc * 0.6) + (desvio_grasa * 0.4))\n",
    "\n",
    "    return round(imc, 1), round(pct_grasa, 1), int(calorias), edad_metabolica\n",
    "\n",
    "# --- FUNCIÓN PARA LIMPIAR Y GENERAR WHATSAPP (COLOMBIA) ---\n",
    "def link_whatsapp(num_celular, nombre_cliente, mensaje=\"\"):\n",
    "    num_limpio = str(num_celular).strip().split('.')[0].replace(\" \", \"\").replace(\"-\", \"\")\n",
    "    if not num_limpio.startswith(\"57\"):\n",
    "        num_limpio = \"57\" + num_limpio\n",
    "        \n",
    "    if not mensaje:\n",
    "        mensaje = f\"💪 ¡Hola {nombre_cliente}! Te saludamos de tu plan de Entrenamiento Personalizado. ¡Queremos revisar cómo van tus avances!\"\n",
    "        \n",
    "    return f\"https://wa.me/{num_limpio}?text={urllib.parse.quote(mensaje)}\"\n",
    "\n",
    "# --- CARGAR DATOS DESDE GOOGLE SHEETS ---\n",
    "@st.cache_data(ttl=10)\n",
    "def cargar_bd():\n",
    "    try:\n",
    "        res = requests.get(URL_API).json()\n",
    "        \n",
    "        df_u = pd.DataFrame(res.get(\"usuarios\", []))\n",
    "        if not df_u.empty and len(df_u) > 1:\n",
    "            df_u.columns = df_u.iloc[0]\n",
    "            df_u = df_u[1:]\n",
    "        else:\n",
    "            df_u = pd.DataFrame(columns=[\"cedula\", \"nombre_completo\", \"whatsapp\", \"eps\", \"condiciones_medicas\", \"rol\", \"password\", \"fecha_registro\"])\n",
    "\n",
    "        df_m = pd.DataFrame(res.get(\"historial\", []))\n",
    "        if not df_m.empty and len(df_m) > 1:\n",
    "            df_m.columns = df_m.iloc[0]\n",
    "            df_m = df_m[1:]\n",
    "        else:\n",
    "            df_m = pd.DataFrame(columns=[\"id_registro\", \"fecha_evaluacion\", \"cedula\", \"edad\", \"sexo\", \"meta\", \"peso_kg\", \"estatura_cm\", \"cuello_cm\", \"hombros_cm\", \"bicep_der_cm\", \"bicep_izq_cm\", \"pecho_cm\", \"cintura_cm\", \"cadera_cm\", \"pierna_der_cm\", \"pierna_izq_cm\", \"gemelo_der_cm\", \"gemelo_izq_cm\", \"imc\", \"porcentaje_grasa\", \"calorias_objetivo\", \"edad_metabolica\"])\n",
    "\n",
    "        return df_u, df_m\n",
    "    except Exception as e:\n",
    "        st.error(f\"Error al conectar con Google Sheets: {e}\")\n",
    "        return pd.DataFrame(), pd.DataFrame()\n",
    "\n",
    "df_usuarios, df_historial = cargar_bd()\n",
    "\n",
    "# --- AUTENTICACIÓN / SESIÓN ---\n",
    "if \"autenticado\" not in st.session_state:\n",
    "    st.session_state[\"autenticado\"] = False\n",
    "    st.session_state[\"rol\"] = None\n",
    "    st.session_state[\"cedula\"] = None\n",
    "    st.session_state[\"nombre\"] = None\n",
    "\n",
    "st.title(\"🏋️‍♂️ PERSONAL TRAINING & EVOLUTION TRACKER\")\n",
    "\n",
    "# --- LOGIN / REGISTRO ---\n",
    "if not st.session_state[\"autenticado\"]:\n",
    "    col1, col2 = st.columns(2)\n",
    "    \n",
    "    with col1:\n",
    "        st.subheader(\"🔐 Iniciar Sesión\")\n",
    "        cedula_ingreso = st.text_input(\"Número de Cédula / ID:\").strip()\n",
    "        pass_ingreso = st.text_input(\"Contraseña:\", type=\"password\").strip()\n",
    "        \n",
    "        if st.button(\"Ingresar\", use_container_width=True):\n",
    "            if cedula_ingreso == \"admin\" and pass_ingreso == \"admin123\":\n",
    "                st.session_state[\"autenticado\"] = True\n",
    "                st.session_state[\"rol\"] = \"Admin\"\n",
    "                st.session_state[\"cedula\"] = \"ADMIN\"\n",
    "                st.session_state[\"nombre\"] = \"Administrador\"\n",
    "                st.rerun()\n",
    "            elif not df_usuarios.empty and cedula_ingreso in df_usuarios[\"cedula\"].astype(str).values:\n",
    "                u = df_usuarios[df_usuarios[\"cedula\"].astype(str) == cedula_ingreso].iloc[0]\n",
    "                if str(u[\"password\"]).strip() == pass_ingreso:\n",
    "                    st.session_state[\"autenticado\"] = True\n",
    "                    st.session_state[\"rol\"] = u.get(\"rol\", \"Cliente\")\n",
    "                    st.session_state[\"cedula\"] = str(u[\"cedula\"])\n",
    "                    st.session_state[\"nombre\"] = u[\"nombre_completo\"]\n",
    "                    st.rerun()\n",
    "                else:\n",
    "                    st.error(\"❌ Contraseña incorrecta.\")\n",
    "            else:\n",
    "                st.error(\"❌ Cédula no registrada.\")\n",
    "\n",
    "    with col2:\n",
    "        st.subheader(\"📝 Crear Cuenta Nueva\")\n",
    "        with st.form(\"form_registro\"):\n",
    "            reg_cedula = st.text_input(\"Número de Cédula / ID:\").strip()\n",
    "            reg_nombre = st.text_input(\"Nombre Completo:\").strip()\n",
    "            reg_whatsapp = st.text_input(\"Número de Celular (10 dígitos Colombia):\", placeholder=\"3101234567\").strip()\n",
    "            reg_eps = st.text_input(\"EPS / Seguro de Salud:\").strip()\n",
    "            reg_condiciones = st.text_area(\"Condiciones Médicas / Lesiones / Cirugías:\").strip()\n",
    "            reg_pass = st.text_input(\"Crea tu Contraseña:\", type=\"password\").strip()\n",
    "            \n",
    "            if st.form_submit_button(\"Crear Perfil\"):\n",
    "                if not reg_cedula or not reg_nombre or not reg_pass:\n",
    "                    st.error(\"⚠️ Cédula, Nombre y Contraseña son obligatorios.\")\n",
    "                elif not df_usuarios.empty and reg_cedula in df_usuarios[\"cedula\"].astype(str).values:\n",
    "                    st.error(\"❌ Esta cédula ya está registrada.\")\n",
    "                else:\n",
    "                    nueva_fila = [reg_cedula, reg_nombre, reg_whatsapp, reg_eps if reg_eps else \"NINGUNA\", reg_condiciones if reg_condiciones else \"NINGUNA\", \"Cliente\", reg_pass, datetime.today().strftime('%Y-%m-%d')]\n",
    "                    try:\n",
    "                        requests.post(URL_API, json={\"action\": \"registrar_usuario\", \"row\": nueva_fila})\n",
    "                        st.cache_data.clear()\n",
    "                        st.success(\"🎉 ¡Perfil creado con éxito! Ya puedes iniciar sesión.\")\n",
    "                    except Exception as e:\n",
    "                        st.error(f\"Error al guardar usuario: {e}\")\n",
    "\n",
    "# --- PANELES UNA VEZ AUTENTICADO ---\n",
    "else:\n",
    "    st.sidebar.markdown(f\"### 👤 {st.session_state['nombre']}\")\n",
    "    st.sidebar.markdown(f\"**Rol:** {st.session_state['rol']}\")\n",
    "    if st.sidebar.button(\"Cerrar Sesión\"):\n",
    "        st.session_state[\"autenticado\"] = False\n",
    "        st.rerun()\n",
    "\n",
    "    # --- 👤 MÓDULO CLIENTE ---\n",
    "    if st.session_state[\"rol\"] == \"Cliente\":\n",
    "        opcion = st.sidebar.radio(\"MENÚ\", [\"📏 Registrar Medidas Hoy\", \"📊 Ver Mi Progreso\"])\n",
    "        \n",
    "        if opcion == \"📏 Registrar Medidas Hoy\":\n",
    "            st.subheader(\"Registro de Evaluación Antropométrica\")\n",
    "            with st.form(\"form_medidas_cliente\"):\n",
    "                c1, c2, c3 = st.columns(3)\n",
    "                peso = c1.number_input(\"Peso (kg):\", 30.0, 200.0, 70.0, 0.5)\n",
    "                estatura = c2.number_input(\"Estatura (cm):\", 100.0, 220.0, 170.0, 1.0)\n",
    "                edad = c3.number_input(\"Edad (años):\", 10, 90, 25)\n",
    "                \n",
    "                sexo = c1.selectbox(\"Sexo Fisiológico:\", [\"Masculino\", \"Femenino\"])\n",
    "                meta = c2.selectbox(\"Objetivo Principal:\", [\"Perder Grasa\", \"Ganar Músculo\", \"Mantenimiento\"])\n",
    "                \n",
    "                st.markdown(\"---\")\n",
    "                st.write(\"**Medidas Corporales (cm)**\")\n",
    "                m1, m2, m3, m4 = st.columns(4)\n",
    "                cuello = m1.number_input(\"Cuello:\", 20.0, 60.0, 38.0)\n",
    "                hombros = m2.number_input(\"Hombros:\", 50.0, 180.0, 110.0)\n",
    "                pecho = m3.number_input(\"Pecho:\", 50.0, 180.0, 95.0)\n",
    "                cintura = m4.number_input(\"Cintura / Abdomen:\", 40.0, 180.0, 80.0)\n",
    "                \n",
    "                bicep_der = m1.number_input(\"Bícep Der:\", 15.0, 60.0, 32.0)\n",
    "                bicep_izq = m2.number_input(\"Bícep Izq:\", 15.0, 60.0, 32.0)\n",
    "                cadera = m3.number_input(\"Glúteos / Cadera:\", 40.0, 180.0, 95.0)\n",
    "                pierna_der = m4.number_input(\"Pierna Der:\", 20.0, 90.0, 55.0)\n",
    "                \n",
    "                pierna_izq = m1.number_input(\"Pierna Izq:\", 20.0, 90.0, 55.0)\n",
    "                gemelo_der = m2.number_input(\"Gemelo Der:\", 15.0, 60.0, 35.0)\n",
    "                gemelo_izq = m3.number_input(\"Gemelo Izq:\", 15.0, 60.0, 35.0)\n",
    "                \n",
    "                if st.form_submit_button(\"Guardar Evaluación\"):\n",
    "                    imc, grasa, cals, edad_bio = calcular_metricas(peso, estatura, edad, sexo, cuello, cintura, cadera, meta)\n",
    "                    \n",
    "                    id_reg = f\"{st.session_state['cedula']}_{datetime.today().strftime('%Y%m%d%H%M')}\"\n",
    "                    fecha_hoy = datetime.today().strftime('%Y-%m-%d')\n",
    "                    \n",
    "                    fila_medidas = [id_reg, fecha_hoy, st.session_state['cedula'], edad, sexo, meta, peso, estatura, cuello, hombros, bicep_der, bicep_izq, pecho, cintura, cadera, pierna_der, pierna_izq, gemelo_der, gemelo_izq, imc, grasa, cals, edad_bio]\n",
    "                    \n",
    "                    try:\n",
    "                        requests.post(URL_API, json={\"action\": \"guardar_medidas\", \"row\": fila_medidas})\n",
    "                        st.cache_data.clear()\n",
    "                        st.success(\"🎉 ¡Medidas guardadas con éxito!\")\n",
    "                        \n",
    "                        r1, r2, r3, r4 = st.columns(4)\n",
    "                        r1.metric(\"IMC\", f\"{imc}\")\n",
    "                        r2.metric(\"% Grasa Estimada\", f\"{grasa}%\")\n",
    "                        r3.metric(\"Calorías Recomendadas\", f\"{cals} kcal\")\n",
    "                        r4.metric(\"Edad Aparentada (Salud)\", f\"{edad_bio} años\")\n",
    "                    except Exception as e:\n",
    "                        st.error(f\"Error al enviar datos: {e}\")\n",
    "\n",
    "        elif opcion == \"📊 Ver Mi Progreso\":\n",
    "            st.subheader(\"📉 Comparativa de Evolución\")\n",
    "            mis_registros = df_historial[df_historial[\"cedula\"].astype(str) == st.session_state['cedula']] if not df_historial.empty else pd.DataFrame()\n",
    "            \n",
    "            if len(mis_registros) >= 2:\n",
    "                mis_registros = mis_registros.sort_values(by=\"fecha_evaluacion\")\n",
    "                inicial = mis_registros.iloc[0]\n",
    "                actual = mis_registros.iloc[-1]\n",
    "                \n",
    "                diff_peso = float(actual[\"peso_kg\"]) - float(inicial[\"peso_kg\"])\n",
    "                diff_cintura = float(actual[\"cintura_cm\"]) - float(inicial[\"cintura_cm\"])\n",
    "                diff_grasa = float(actual[\"porcentaje_grasa\"]) - float(inicial[\"porcentaje_grasa\"])\n",
    "                \n",
    "                st.info(f\"📊 **Resumen desde tu primer registro ({inicial['fecha_evaluacion']}) hasta hoy ({actual['fecha_evaluacion']}):**\")\n",
    "                \n",
    "                c1, c2, c3 = st.columns(3)\n",
    "                c1.metric(\"Variación de Peso\", f\"{actual['peso_kg']} kg\", f\"{diff_peso:.1f} kg\")\n",
    "                c2.metric(\"Variación de Cintura\", f\"{actual['cintura_cm']} cm\", f\"{diff_cintura:.1f} cm\")\n",
    "                c3.metric(\"Variación % Grasa\", f\"{actual['porcentaje_grasa']}%\", f\"{diff_grasa:.1f}%\")\n",
    "                \n",
    "                st.dataframe(mis_registros, use_container_width=True)\n",
    "            elif len(mis_registros) == 1:\n",
    "                st.warning(\"Solo tienes 1 registro guardado. Registra tus medidas el próximo mes para ver la comparativa de avance.\")\n",
    "                st.dataframe(mis_registros, use_container_width=True)\n",
    "            else:\n",
    "                st.info(\"Aún no has registrado ninguna evaluación.\")\n",
    "\n",
    "    # --- 👑 MÓDULO ADMINISTRADOR ---\n",
    "    elif st.session_state[\"rol\"] == \"Admin\":\n",
    "        st.subheader(\"👑 Panel de Control General\")\n",
    "        \n",
    "        if not df_usuarios.empty:\n",
    "            clientes = df_usuarios[df_usuarios[\"rol\"] == \"Cliente\"]\n",
    "            \n",
    "            st.markdown(f\"**Total de Clientes Registrados:** {len(clientes)}\")\n",
    "            \n",
    "            cedula_sel = st.selectbox(\"Buscar Cliente por Nombre/Cédula:\", clientes[\"cedula\"].astype(str) + \" - \" + clientes[\"nombre_completo\"])\n",
    "            \n",
    "            if cedula_sel:\n",
    "                id_cliente = cedula_sel.split(\" - \")[0]\n",
    "                u_info = clientes[clientes[\"cedula\"].astype(str) == id_cliente].iloc[0]\n",
    "                \n",
    "                st.markdown(\"---\")\n",
    "                col_u1, col_u2 = st.columns([3, 1])\n",
    "                with col_u1:\n",
    "                    st.markdown(f\"\"\"\n",
    "                    * **Nombre:** {u_info['nombre_completo']}\n",
    "                    * **Cédula:** {u_info['cedula']}\n",
    "                    * **EPS:** {u_info['eps']}\n",
    "                    * **Condiciones Físicas:** {u_info['condiciones_medicas']}\n",
    "                    \"\"\")\n",
    "                with col_u2:\n",
    "                    ws_url = link_whatsapp(u_info['whatsapp'], u_info['nombre_completo'])\n",
    "                    st.link_button(\"💬 Enviar WhatsApp\", ws_url, use_container_width=True)\n",
    "                    \n",
    "                st.markdown(\"---\")\n",
    "                st.subheader(\"📈 Historial de Avances del Cliente\")\n",
    "                h_cliente = df_historial[df_historial[\"cedula\"].astype(str) == id_cliente] if not df_historial.empty else pd.DataFrame()\n",
    "                \n",
    "                if not h_cliente.empty:\n",
    "                    st.dataframe(h_cliente, use_container_width=True)\n",
    "                else:\n",
    "                    st.warning(\"Este cliente aún no ha ingresado registros de medidas.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "099982f6-a8d7-4774-b30f-d71aa0388b56",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
